### ISSUE TITLE
Can't render results (positive or negative value) in the browser. 

### ISSUE THREAD

**Issue by Shosho85** [Shosho85/sentiment_analysis#1]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

To show on the browser whether a text is positive or negative.

By using an Alchemy API, i can't figure out how to render the information in the browser regarding the string/text is positive or negative. 
- After cloning the AlchemyAPI files from github that's provided, tested test.rb/example.rb file and works in terminal (however not sure how to work it in the browser).
- I tried using a script tag to render the results from the test.rb file (guessing that this doesn't work in ruby??)
- Tried testing one of the method defined in AlchemyAPI class but gives an error message saying: 

```
NoMethodError: undefined method `sentiment' for AlchemyAPI:Class
```

I seeded my own database table so rendering that information works, and so far, i'm able to have users input the text and type (positive or negative) themselves.

**Comment by WilliamfShaw** [comment]
@Shosho85 the error is revolving trying to use the `sentiment` method. You have no defined it so the api has no idea what to use. Can you please try to resolve this issue or give us a little more information regarding what you have tried.

**Comment by WilliamfShaw** [comment]
@Shosho85 can you also push the most recent version of your code

**Comment by Shosho85** [comment]
sure, i think i might have to create a seperate controller? Let me see if i can figure it out. 
and yes my apologies, i completely forgot to put the recent version of my code....just pushed my current version of the code

**Comment by harimohanraj89** [comment]
I'm going to close this for now. If the issue persists, go ahead and reopen the issue @Shosho85 .

**Comment by Shosho85** [comment]
Okay

**Comment by Shosho85** [comment]
I feel like i’m completely lost on this same issue. 
- sentiment method is already defined in alchemyapi.rb inside of the AlchemyAPI class. Also, does this require a view or a controller since its not interacting with my database table?
- i looked at the AlchemyAPI docs and it seems confusing in regards to the available parameters. Not sure how to go about it since its already set up in the alchemyapi.rb file.  http://www.alchemyapi.com/api/sentiment/urls.html#textsentiment
- also looked at Hari’s lecture video on omdb to understand the logic of setting up and connecting to an API but seems confusing with the way AlchemyAPI has its files set up.

**Comment by bigtone1284** [comment]
taken
